@url_dev=http://localhost:8080/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "email": "shop@gmail.com", 
    "password": "abc123"
}


### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 

{
    "email": "shop11@gmail.com",
    "password": "abc123"
}

### logout
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 
x-client-key:
authorization: 

{
    "email": "shop11@gmail.com",
    "password": "abc123"
}
